name: event_batch
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  firebase_core: ^2.24.2
  permission_handler: ^11.1.0
  universal_html: ^2.2.4
  flutter_bloc: ^8.1.3
  super_extensions: ^0.0.7
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  seo_renderer: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/
